### ISSUE TITLE
容器初始化报错

### ISSUE THREAD

**Issue by wbkohan** [nelivacn/FAT-selfTest#1]
按README执行了所有的步骤，但通过测试页面进行“初始化”时，页面无反应
![image](https://github.com/nelivacn/FAT-selfTest/assets/16113932/2051c9a1-d1e3-4860-b8b6-ffdcaafc9068)
在/workspace/script/selftest/out.log日志文件中，发现错误提示：
`com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'\nnvidia-container-cli: device error: 1: unknown device: unknown"}`

**Comment by msbrm** [comment]
服务器环境可以提供吗 显卡 Docker版本相关的信息
![image](https://github.com/nelivacn/FAT-selfTest/assets/112378987/58562d48-951d-4591-9ed3-bf1f9c6c867e)
这部分的输出是什么

**Comment by wbkohan** [comment]
Docker版本信息是：Docker version 20.10.21, build 20.10.21-0ubuntu1~18.04.3
![image](https://github.com/nelivacn/FAT-selfTest/assets/16113932/551a9f82-3cc2-4aca-9e9b-a9a166c5063a)
输出看起来是正常的

**Comment by nelivacn** [comment]
如果测试项目是1N1,服务器上至少需要两块显卡
