### ISSUE TITLE
测试脚本script/pys/vehicle.p存在未定义参数

### ISSUE THREAD

**Issue by Aqdjuly** [nelivacn/FAT-selfTest#10]
https://github.com/nelivacn/FAT-selfTest/blob/main/script/pys/vehicle.py#L132C55-L132C61 
该处 DEVICE 未定义

脚本执行时会报错，导致自助测试失败
-NameError: name 'DEVICE' is not defined

**Comment by xinmaoge** [comment]
同样的问题

**Comment by msbrm** [comment]
已经更新 删除 DEVICE 变量打印
