### ISSUE TITLE
无法执行env_restart.sh

### ISSUE THREAD

**Issue by 411104983** [nelivacn/FAT-selfTest#11]
人脸测试时，执行env_restart.sh报错No sush file or directory。
![企业微信截图_17204092377446](https://github.com/nelivacn/FAT-selfTest/assets/33622122/444f56a3-7462-4ef2-9f24-d936d82a4ae9)
已经确保容器内此路径下存在此脚本，并且sh env_restart.sh在容器内可以正常执行。

**Comment by msbrm** [comment]
env_restart.sh 这个脚本里有用到其他文件吗

**Comment by 411104983** [comment]
> env_restart.sh脚本里有用其他文件吗
没有其他文件，env_restart.sh 的内容相对简单，不会出现无法运行的情况
