### ISSUE TITLE
自助测试页面可选镜像版本与ReadME中selftest镜像版本不一致

### ISSUE THREAD

**Issue by Aqdjuly** [nelivacn/FAT-selfTest#3]
![image](https://github.com/nelivacn/FAT-selfTest/assets/171911600/b5286974-e03a-4eca-b4b9-c0d4e8bc8c8e)
[README](https://github.com/nelivacn/FAT-selfTest/tree/main/#)中镜像版本为V2024.2
页面可选为V2024.1

**Comment by msbrm** [comment]
我们更新一下
可以先docker tag 更改拉取到本地的镜像标签
