### ISSUE TITLE
自助测试镜像拉取失败问题

### ISSUE THREAD

**Issue by Aqdjuly** [nelivacn/FAT-selfTest#5]
![image](https://github.com/nelivacn/FAT-selfTest/assets/171911600/ef05832f-29d6-4b78-9ca0-123146dedeb7)
docker pull nelivacn/fat:cuda11.4.3-ubuntu18.04-selftestV2024.1
执行失败，镜像拉取不成功

**Comment by msbrm** [comment]
过几分钟重试一下
